import React from "react";
import './CipherMap.css'
import CLbox from "./CLbox";

function CipherMap() {
  return (
    <div className="cipherMap">
      <h2>Cipher Map</h2>
      <div className="cl-container">
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
        <CLbox />
      </div>
    </div>
  );
}

export default CipherMap;
